################################################################################
# Judge0 Configuration File
################################################################################
# Judge0 is a robust and scalable open-source online code execution system.
# Please visit https://judge0.com for more information.

# REDIS
REDIS_PASSWORD=YourSecurePassword123

# POSTGRES
POSTGRES_HOST=db
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=YourSecurePassword123

# CORE
ENABLE_WAIT_RESULT=true
ENABLE_COMPILER_OPTIONS=true
ALLOWED_LANGUAGES_FOR_COMPILE_OPTIONS=44,45,46,47,48,49,50,51,52,53,54

# OPTIONAL
ENABLE_SUBMISSION_DELETE=false
ENABLE_CALLBACKS=false
CALLBACKS_MAX_TRIES=3
CALLBACKS_TIMEOUT=5

MAINTENANCE_MODE=false
ENABLE_DOCS=true